### Normalization

In [17]:
import pandas as pd
from sklearn.datasets import make_classification

In [39]:
# criando dataframe com 1000 linhas e 10 colunas
dados = sklearn.datasets.make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, n_clusters_per_class=2, random_state=0)

df = pd.DataFrame(dados[0])
df

,0,1,2,3,4,5,6,7,8,9
0,0.222786,0.870564,-3.290810,1.117830,1.755358,-0.437049,0.287107,-1.584008,-0.162968,1.902158
1,-0.806599,2.684316,0.955526,4.973821,-2.888940,4.637688,-2.769496,-1.406006,-0.332930,1.808836
2,0.455188,-0.677934,-0.997042,-0.225333,1.270827,0.155836,-1.020962,-0.683375,0.849723,1.196119
3,-0.538257,1.659121,4.456966,2.701980,-4.116475,3.429122,-3.893045,1.673449,1.227027,1.291036
4,-1.241303,-1.185817,1.870198,-1.186417,0.388352,0.994241,-1.945188,0.863679,0.708342,-0.166214
...,...,...,...,...,...,...,...,...,...,...
995,-3.410886,1.284570,2.444467,-0.312095,-0.639665,0.179275,-1.306014,2.632384,-0.460471,-0.018220
996,-1.622222,3.175516,1.022117,2.437494,-2.452569,0.442384,0.286981,1.248686,-1.242949,0.311679
997,-0.969295,2.563164,1.152350,1.801718,-2.168705,0.050517,-0.150726,1.487738,-0.486027,0.674164
998,-1.327055,-0.776937,1.048556,-1.000730,0.753513,0.537684,-1.488143,0.696726,0.457952,0.113858
999,2.852121,-2.171140,0.631375,-0.254425,-0.554769,1.317042,-0.765427,-1.433610,1.337172,-0.462320

In [42]:
def normalizacao(x):
    return (x - x.mean()) / (.00001 + x.std()) # evitando divisÃ£o por zero

df_normalized = df.apply(normalizacao)
df_normalized

,0,1,2,3,4,5,6,7,8,9
0,0.472491,-0.199657,-1.314262,-0.156853,1.629388,-0.550506,0.472435,-1.074059,0.007262,0.628751
1,-0.212900,0.554317,0.524194,1.736766,-1.649979,2.275423,-1.330533,-0.951399,-0.117507,0.563167
2,0.627230,-0.843366,-0.321172,-0.816461,1.287258,-0.220351,-0.299142,-0.453436,0.750684,0.132563
3,-0.034230,0.128145,2.040147,0.621099,-2.516749,1.602419,-1.993270,1.170643,1.027665,0.199268
4,-0.502336,-1.054492,0.920203,-1.288434,0.664137,0.246526,-0.844307,0.612634,0.646895,-0.824854
...,...,...,...,...,...,...,...,...,...,...
995,-1.946899,-0.027555,1.168833,-0.859068,-0.061752,-0.207298,-0.467283,1.831442,-0.211136,-0.720848
996,-0.755962,0.758508,0.553025,0.491214,-1.341855,-0.060783,0.472361,0.877940,-0.785557,-0.489002
997,-0.321227,0.503954,0.609410,0.178994,-1.141417,-0.278998,0.214175,1.042671,-0.229897,-0.234255
998,-0.559432,-0.884521,0.564472,-1.197246,0.921979,-0.007714,-0.574714,0.497587,0.463083,-0.628026
999,2.223168,-1.464089,0.383853,-0.830747,-0.001807,0.426281,-0.148413,-0.970421,1.108523,-1.032951

In [41]:
df.describe()

,0,1,2,3,4,5,6,7,8,9
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,-0.486846,1.350857,-0.255221,1.437232,-0.552211,0.551536,-0.513821,-0.025360,-0.172861,1.007492
std,1.501886,2.405579,2.309719,2.036297,1.416208,1.795766,1.695307,1.451165,1.362193,1.422915
min,-4.370126,-6.938088,-8.677560,-5.356204,-4.947015,-5.035840,-5.427132,-4.835715,-4.455689,-4.193473
25%,-1.544418,-0.298664,-1.764476,0.075129,-1.519200,-0.605190,-1.636641,-1.078525,-1.091854,0.077178
50%,-0.589513,1.487689,-0.189870,1.410913,-0.622664,0.439798,-0.585809,0.446206,-0.411285,1.047915
75%,0.528093,3.083920,1.371988,2.580561,0.362746,1.679117,0.577295,1.082422,0.748632,2.012476
max,4.116388,7.842495,6.197152,8.934095,4.985826,6.948074,5.414044,3.785975,4.772964,6.099143